/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as MoviesIndexRouteImport } from './routes/movies/index'
import { Route as DiscoverIndexRouteImport } from './routes/discover/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as UserUserIdIndexRouteImport } from './routes/user/$userId/index'
import { Route as PersonPersonIdIndexRouteImport } from './routes/person/$personId/index'
import { Route as MoviesMovieIdIndexRouteImport } from './routes/movies/$movieId/index'
import { Route as ListsListIdIndexRouteImport } from './routes/lists/$listId/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedUserSettingsIndexRouteImport } from './routes/_authenticated/user/settings/index'
import { Route as AuthenticatedUserActivityIndexRouteImport } from './routes/_authenticated/user/activity/index'
import { Route as AuthenticatedUserUserIdWatchlistIndexRouteImport } from './routes/_authenticated/user/$userId/watchlist/index'
import { Route as AuthenticatedUserUserIdDiaryIndexRouteImport } from './routes/_authenticated/user/$userId/diary/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverIndexRoute = DiscoverIndexRouteImport.update({
  id: '/discover/',
  path: '/discover/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUserIdIndexRoute = UserUserIdIndexRouteImport.update({
  id: '/user/$userId/',
  path: '/user/$userId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonPersonIdIndexRoute = PersonPersonIdIndexRouteImport.update({
  id: '/person/$personId/',
  path: '/person/$personId/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesMovieIdIndexRoute = MoviesMovieIdIndexRouteImport.update({
  id: '/movies/$movieId/',
  path: '/movies/$movieId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsListIdIndexRoute = ListsListIdIndexRouteImport.update({
  id: '/lists/$listId/',
  path: '/lists/$listId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUserSettingsIndexRoute =
  AuthenticatedUserSettingsIndexRouteImport.update({
    id: '/user/settings/',
    path: '/user/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserActivityIndexRoute =
  AuthenticatedUserActivityIndexRouteImport.update({
    id: '/user/activity/',
    path: '/user/activity/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserUserIdWatchlistIndexRoute =
  AuthenticatedUserUserIdWatchlistIndexRouteImport.update({
    id: '/user/$userId/watchlist/',
    path: '/user/$userId/watchlist/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserUserIdDiaryIndexRoute =
  AuthenticatedUserUserIdDiaryIndexRouteImport.update({
    id: '/user/$userId/diary/',
    path: '/user/$userId/diary/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/about/': typeof AboutIndexRoute
  '/discover/': typeof DiscoverIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/search/': typeof SearchIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/lists/$listId/': typeof ListsListIdIndexRoute
  '/movies/$movieId/': typeof MoviesMovieIdIndexRoute
  '/person/$personId/': typeof PersonPersonIdIndexRoute
  '/user/$userId/': typeof UserUserIdIndexRoute
  '/user/activity/': typeof AuthenticatedUserActivityIndexRoute
  '/user/settings/': typeof AuthenticatedUserSettingsIndexRoute
  '/user/$userId/diary/': typeof AuthenticatedUserUserIdDiaryIndexRoute
  '/user/$userId/watchlist/': typeof AuthenticatedUserUserIdWatchlistIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/about': typeof AboutIndexRoute
  '/discover': typeof DiscoverIndexRoute
  '/movies': typeof MoviesIndexRoute
  '/search': typeof SearchIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/lists/$listId': typeof ListsListIdIndexRoute
  '/movies/$movieId': typeof MoviesMovieIdIndexRoute
  '/person/$personId': typeof PersonPersonIdIndexRoute
  '/user/$userId': typeof UserUserIdIndexRoute
  '/user/activity': typeof AuthenticatedUserActivityIndexRoute
  '/user/settings': typeof AuthenticatedUserSettingsIndexRoute
  '/user/$userId/diary': typeof AuthenticatedUserUserIdDiaryIndexRoute
  '/user/$userId/watchlist': typeof AuthenticatedUserUserIdWatchlistIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/about/': typeof AboutIndexRoute
  '/discover/': typeof DiscoverIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/search/': typeof SearchIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/lists/$listId/': typeof ListsListIdIndexRoute
  '/movies/$movieId/': typeof MoviesMovieIdIndexRoute
  '/person/$personId/': typeof PersonPersonIdIndexRoute
  '/user/$userId/': typeof UserUserIdIndexRoute
  '/_authenticated/user/activity/': typeof AuthenticatedUserActivityIndexRoute
  '/_authenticated/user/settings/': typeof AuthenticatedUserSettingsIndexRoute
  '/_authenticated/user/$userId/diary/': typeof AuthenticatedUserUserIdDiaryIndexRoute
  '/_authenticated/user/$userId/watchlist/': typeof AuthenticatedUserUserIdWatchlistIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/about/'
    | '/discover/'
    | '/movies/'
    | '/search/'
    | '/admin/'
    | '/lists/$listId/'
    | '/movies/$movieId/'
    | '/person/$personId/'
    | '/user/$userId/'
    | '/user/activity/'
    | '/user/settings/'
    | '/user/$userId/diary/'
    | '/user/$userId/watchlist/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/about'
    | '/discover'
    | '/movies'
    | '/search'
    | '/admin'
    | '/lists/$listId'
    | '/movies/$movieId'
    | '/person/$personId'
    | '/user/$userId'
    | '/user/activity'
    | '/user/settings'
    | '/user/$userId/diary'
    | '/user/$userId/watchlist'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/about/'
    | '/discover/'
    | '/movies/'
    | '/search/'
    | '/_authenticated/admin/'
    | '/lists/$listId/'
    | '/movies/$movieId/'
    | '/person/$personId/'
    | '/user/$userId/'
    | '/_authenticated/user/activity/'
    | '/_authenticated/user/settings/'
    | '/_authenticated/user/$userId/diary/'
    | '/_authenticated/user/$userId/watchlist/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AboutIndexRoute: typeof AboutIndexRoute
  DiscoverIndexRoute: typeof DiscoverIndexRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  ListsListIdIndexRoute: typeof ListsListIdIndexRoute
  MoviesMovieIdIndexRoute: typeof MoviesMovieIdIndexRoute
  PersonPersonIdIndexRoute: typeof PersonPersonIdIndexRoute
  UserUserIdIndexRoute: typeof UserUserIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies/'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/': {
      id: '/discover/'
      path: '/discover'
      fullPath: '/discover/'
      preLoaderRoute: typeof DiscoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$userId/': {
      id: '/user/$userId/'
      path: '/user/$userId'
      fullPath: '/user/$userId/'
      preLoaderRoute: typeof UserUserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$personId/': {
      id: '/person/$personId/'
      path: '/person/$personId'
      fullPath: '/person/$personId/'
      preLoaderRoute: typeof PersonPersonIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$movieId/': {
      id: '/movies/$movieId/'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId/'
      preLoaderRoute: typeof MoviesMovieIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/$listId/': {
      id: '/lists/$listId/'
      path: '/lists/$listId'
      fullPath: '/lists/$listId/'
      preLoaderRoute: typeof ListsListIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/settings/': {
      id: '/_authenticated/user/settings/'
      path: '/user/settings'
      fullPath: '/user/settings/'
      preLoaderRoute: typeof AuthenticatedUserSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/activity/': {
      id: '/_authenticated/user/activity/'
      path: '/user/activity'
      fullPath: '/user/activity/'
      preLoaderRoute: typeof AuthenticatedUserActivityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/$userId/watchlist/': {
      id: '/_authenticated/user/$userId/watchlist/'
      path: '/user/$userId/watchlist'
      fullPath: '/user/$userId/watchlist/'
      preLoaderRoute: typeof AuthenticatedUserUserIdWatchlistIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/$userId/diary/': {
      id: '/_authenticated/user/$userId/diary/'
      path: '/user/$userId/diary'
      fullPath: '/user/$userId/diary/'
      preLoaderRoute: typeof AuthenticatedUserUserIdDiaryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedUserActivityIndexRoute: typeof AuthenticatedUserActivityIndexRoute
  AuthenticatedUserSettingsIndexRoute: typeof AuthenticatedUserSettingsIndexRoute
  AuthenticatedUserUserIdDiaryIndexRoute: typeof AuthenticatedUserUserIdDiaryIndexRoute
  AuthenticatedUserUserIdWatchlistIndexRoute: typeof AuthenticatedUserUserIdWatchlistIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedUserActivityIndexRoute: AuthenticatedUserActivityIndexRoute,
  AuthenticatedUserSettingsIndexRoute: AuthenticatedUserSettingsIndexRoute,
  AuthenticatedUserUserIdDiaryIndexRoute:
    AuthenticatedUserUserIdDiaryIndexRoute,
  AuthenticatedUserUserIdWatchlistIndexRoute:
    AuthenticatedUserUserIdWatchlistIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AboutIndexRoute: AboutIndexRoute,
  DiscoverIndexRoute: DiscoverIndexRoute,
  MoviesIndexRoute: MoviesIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  ListsListIdIndexRoute: ListsListIdIndexRoute,
  MoviesMovieIdIndexRoute: MoviesMovieIdIndexRoute,
  PersonPersonIdIndexRoute: PersonPersonIdIndexRoute,
  UserUserIdIndexRoute: UserUserIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
